name: HyenaRTP
main: me.hyena.hyenartp.HyenaRTP
version: 1.1.1
api-version: 1.20
description: Random teleport plugin with per-rank cooldown, safe locations, and world access control.
author: GodHyena
commands:
  rtp:
    description: Random teleport
    usage: /rtp <world> OR /rtp <player> <world>
    permission: hyenartp.use
    permission-message: You don't have permission to use this command.