name: HyenaRTP
version: 1.1.1
main: me.hyena.hyenartp.HyenaRTP
api-version: 1.20
commands:
  rtp:
    description: Random teleport command
    usage: /<command> <world> or /<command> <player> <world>
permissions:
  hyenartp.rank.default:
    default: true
  hyenartp.rank.vip:
    default: false
  hyenartp.rank.mvp:
    default: false
  hyenartp.rank.elite:
    default: false