name: Build HyenaRTP Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload Compiled JAR
      uses: actions/upload-artifact@v4
      with:
        name: HyenaRTP.jar
        path: target/HyenaRTP-1.0.0-shaded.jar
